### ISSUE TITLE
Docker Model Runner unable to pull hugging face models on docker engine.

### ISSUE THREAD

**Issue by joshhsoj1902** [docker/model-runner#114]
Trying to use the Docker model runner on a headless docker engine install on an ubuntu server (not docker desktop)

Pulling dockerhub based models works fine. but pulling hugging face based models always fails with this error:

```
$ sudo docker model pull hf.co/bartowski/Llama-3-Groq-8B-Tool-Use-GGUF
Failed to pull model: pulling hf.co/bartowski/llama-3-groq-8b-tool-use-gguf failed with status 500 Internal Server Error: error while pulling model: config type "application/vnd.docker.container.image.v1+json" is unsupported: client supports only models of type "application/vnd.docker.ai.model.config.v0.1+json" and older - try upgrading
```

Pulling these same models on a docker desktop based install seems to work fine every time.

```
$ sudo docker version
Client: Docker Engine - Community
 Version:           28.3.2
 API version:       1.51
 Go version:        go1.24.5
 Git commit:        578ccf6
 Built:             Wed Jul  9 16:13:45 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.3.2
  API version:      1.51 (minimum version 1.24)
  Go version:       go1.24.5
  Git commit:       e77ff99
  Built:            Wed Jul  9 16:13:45 2025
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


$ sudo docker model version
Docker Model Runner version v0.1.33
Docker Engine Kind: Docker Engine
```

**Comment by ilopezluna** [comment]
Hey @joshhsoj1902  could you try again? It should be fixed now

**Comment by joshhsoj1902** [comment]
@ilopezluna is there something in particular I need to update?

I just tried again and i still get the same error.

I tried running `sudo docker model uninstall-runner --images && sudo docker model install-runner` to force an update of the model runner, but it still pulled `v0.1.33` & I don't see any updates in apt for anything docker related. 

Edit: If this helps, My model runner container is running this image `docker/model-runner:latest-cuda` and this is the image sha `"Image": "sha256:8ac8597055aa30876553f945be970ba5348ca8310417232fd1607f159afa1c4b"`

```
$ sudo docker image ls | grep model
docker/model-runner                          latest-cuda                          8ac8597055aa   12 days ago    3.88GB
```

**Comment by xenoscopic** [comment]
@joshhsoj1902 is there any chance you're pulling via an HTTP proxy that might rewrite your User-Agent?

**Comment by joshhsoj1902** [comment]
@xenoscopic Not that I can remember setting up or can find poking around right now.

**Comment by ilopezluna** [comment]
Hi @joshhsoj1902,
Apologies for the inconvenience. It should work without needing to update anything, the issue is related to how we ensure Hugging Face recognizes the client as Docker so that the files you pull are the OCI Artifact containing the model. 
There were new changes today that should help to properly identify Docker clients even without Docker Desktop, so the pull should work now. Could you please try once again 🙏 ?
Thanks in advance!

**Comment by joshhsoj1902** [comment]
@ilopezluna No inconveniences on my end, this what I signed up for trying something in while it's in beta.

I just tried again and it worked 👌 

Thanks so much!
